/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Accessories' : IDL.Null,
  'Laptop' : IDL.Null,
  'Desktop' : IDL.Null,
  'Monitors' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const ShopInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getShopInfo' : IDL.Func([], [ShopInfo], ['query']),
  'resetData' : IDL.Func([], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Bool],
      [],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Accessories' : IDL.Null,
    'Laptop' : IDL.Null,
    'Desktop' : IDL.Null,
    'Monitors' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ShopInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getShopInfo' : IDL.Func([], [ShopInfo], ['query']),
    'resetData' : IDL.Func([], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Bool],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };