/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Accessories' : null } |
  { 'Laptop' : null } |
  { 'Desktop' : null } |
  { 'Monitors' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : number,
}
export interface Service {
  'id' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface ShopInfo {
  'hours' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, number, Category, boolean],
    bigint
  >,
  'addService' : ActorMethod<[string, string, number, string], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getService' : ActorMethod<[bigint], Service>,
  'getShopInfo' : ActorMethod<[], ShopInfo>,
  'resetData' : ActorMethod<[], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, Category, boolean],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, number, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];